### Get all contacts
GET http://localhost:3000/contacts

### Get contact by ID
GET http://localhost:3000/contacts/{{_id 68d1090fdbddc9eb95802c5e}}

### Create contact
POST http://localhost:3000/contacts
Content-Type: application/json

{
  "firstName": "Alice",
  "lastName": "Smith",
  "email": "alice@example.com",
  "favoriteColor": "Blue",
  "birthday": "1990-01-01"
}

### Update contact
PUT http://localhost:3000/contacts/{{_id 68d10713dbddc9eb95802c5c}}
Content-Type: application/json

{
  "firstName": "Alice",
  "lastName": "Johnson",
  "email": "alice.j@example.com",
  "favoriteColor": "Green",
  "birthday": "1990-01-01"
}

### Delete contact
DELETE http://localhost:3000/contacts/{{_id 68d10878dbddc9eb95802c5d}}
