### Get all contacts
GET http://localhost:3006/project1

### Get contact by ID
GET http://localhost:3006/project1/{{_id 68cfc6db82f909664b033a56}}

### Create contact
POST http://localhost:3006/project1
Content-Type: application/json

{
  "firstName": "Jane",
  "lastName": "Doe",
  "email": "jane@example.com",
  "favoriteColor": "Purple",
  "birthday": "1992-06-15"
}

### Update contact
PUT http://localhost:3006/project1/{{_id 68d56a02c5bb15eb760336f8}}
Content-Type: application/json

{
  "firstName": "Jane",
  "lastName": "Smith",
  "email": "jane.smith@example.com",
  "favoriteColor": "Green",
  "birthday": "1992-06-15"
}

### Delete contact
DELETE http://localhost:3006/project1/{{_id 68d56a92c5bb15eb760336f9}}
