openapi: 3.0.0
info:
  title: Contacts API
  version: 1.0.0
paths:
  /contacts:
    get:
      summary: Get all contacts
      responses:
        '200':
          description: Success
    post:
      summary: Create a contact
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Contact'
      responses:
        '201':
          description: Created
  /contacts/{id}:
    get:
      summary: Get contact by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
    put:
      summary: Update contact
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Contact'
      responses:
        '204':
          description: No Content
    delete:
      summary: Delete contact
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No Content
components:
  schemas:
    Contact:
      type: object
      required:
        - firstName
        - lastName
        - email
        - favoriteColor
        - birthday
      properties:
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        favoriteColor:
          type: string
        birthday:
          type: string
